using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using System.Threading.Tasks;
using System.Globalization;

namespace DJetronicStudio
{
    public class DataPoint
    {
        public double Timestamp;
        public Status Data;

        public DataPoint
            (
            double Timestamp,
            Status Data
            )
        {
            this.Timestamp = Timestamp;
            this.Data = Data;
        }
    }

    public class DataBuffer
    {
        public delegate void OnDataAddedHandler(object sender, int NumPoints, DataPoint NewPoint);
        public event OnDataAddedHandler OnDataAdded = null;

        public delegate void OnDataClearedHandler(object sender);
        public event OnDataClearedHandler OnDataCleared = null;

        public List<DataPoint> Points = new List<DataPoint>();

        public void Clear
            (
            )
        {
            Points.Clear();
            if (OnDataCleared != null) OnDataCleared(this);
        }

        public void Add
            (
            double Timestamp,
            Status Data
            )
        {
            DataPoint NewPoint = new DataPoint(Timestamp, Data);

            Points.Add(NewPoint);
            if (OnDataAdded != null) OnDataAdded(this, Points.Count, NewPoint);
        }

        /// <summary>
        /// Gets the newest data point
        /// </summary>
        /// <returns>Newest data point or null if buffer empty</returns>
        public DataPoint GetNewest
            (
            )
        {
            if (Points.Count == 0)
                return null;
            else
                return Points[Points.Count - 1];
        }

        /// <summary>
        /// Exports the buffer to a CSV file
        /// </summary>
        /// <param name="FileName">Path and name of CSV file to export to</param>
        public void ExportCSV
            (
            string FileName,
            string ApplicationName,
            string ApplicationVersion
            )
        {
            StreamWriter CSVFile = new StreamWriter(FileName, false, Encoding.ASCII);

            try
            {
                CSVFile.WriteLine("Generated by {0} version {1}", ApplicationName, ApplicationVersion);
                CSVFile.WriteLine("Generated on {0}", DateTime.Now);
                CSVFile.WriteLine();

                CSVFile.WriteLine("\"Time (ms)\",\"Pulse Width I (ms)\",\"Pulse Width II (ms)\",\"Pulse Width III (ms)\",\"Pulse Width IV (ms)\",\"Air Temperature (F)\",\"Coolant Temperature (F)\",\"Engine Speed (RPM)\",\"Dwell Angle (Degrees)\",\"Manifold Vacuum (inHg)\",\"Throttle (%)\",\"Fuel Pump\",\"Starter Motor\"");

                foreach (DataPoint DataPoint in Points)
                {
                    CSVFile.WriteLine(String.Format("\"{0}\",\"{1}\",\"{2}\",\"{3}\",\"{4}\",\"{5}\",\"{6}\",\"{7}\",\"{8}\",\"{9}\",\"{10}\",\"{11}\",\"{12}\"",
                        DataPoint.Timestamp.ToString(CultureInfo.CreateSpecificCulture("en-US")),
                        (DataPoint.Data.PulseWidth_I / 1000.0).ToString(CultureInfo.CreateSpecificCulture("en-US")),
                        (DataPoint.Data.PulseWidth_II / 1000.0).ToString(CultureInfo.CreateSpecificCulture("en-US")),
                        (DataPoint.Data.PulseWidth_III / 1000.0).ToString(CultureInfo.CreateSpecificCulture("en-US")),
                        (DataPoint.Data.PulseWidth_IV / 1000.0).ToString(CultureInfo.CreateSpecificCulture("en-US")),
                        (DataPoint.Data.AirTemperature).ToString(CultureInfo.CreateSpecificCulture("en-US")),
                        (DataPoint.Data.CoolantTemperature).ToString(CultureInfo.CreateSpecificCulture("en-US")),
                        (DataPoint.Data.EngineSpeed).ToString(CultureInfo.CreateSpecificCulture("en-US")),
                        (DataPoint.Data.DwellAngle).ToString(CultureInfo.CreateSpecificCulture("en-US")),
                        (DataPoint.Data.Vacuum).ToString(CultureInfo.CreateSpecificCulture("en-US")),
                        (DataPoint.Data.Throttle).ToString(CultureInfo.CreateSpecificCulture("en-US")),
                        (DataPoint.Data.FuelPumpOn ? "1" : "0"),
                        (DataPoint.Data.StarterMotorOn ? "1" : "0")
                        ));
                }
            }
            finally
            {
                CSVFile.Close();
            }
        }
    }
}
